---
name: Template-Provider-CustomDBIC
version: 0.02
author:
  - 'Dave Cardwell <dcardwell@cpan.org>'
abstract: Load templates using DBIx::Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Parse: 0
  File::Path: 0
  File::Spec: 0
  Template::Provider: 0
build_requires:
  DBD::SQLite: 1.11
  DBIx::Class: 0
  Test::More: 0
provides:
  Template::Provider::CustomDBIC:
    file: lib/Template/Provider/CustomDBIC.pm
    version: 0.02
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
